### ISSUE TITLE
[Suggestion] 如果配图的话会不会好一些？

### ISSUE THREAD

**Issue by shanezhiu** [xiaohuilam/laravel#15]
一图胜千言，如果配上图，是不是更好表达，您觉得了？

**Comment by xiaohuilam** [comment]
嗯 好建议 不过插图的话需要结合着用，否则有以下缺点：
- 无法被版本库解析，无法在之前基础上修改。
- 图太吸引注意力，读者看了图不一定愿意看文字了。
 
还有一篇 事件的，我看着画画

**Comment by shanezhiu** [comment]
@xiaohuilam 嗯，第一点是个很大的问题，不过你可以参照[kamranahmedse/developer-roadmap](https://github.com/kamranahmedse/developer-roadmap)这个解决，第二点，我觉得如果一副图片能够说明的事情，文字只能成为辅助。
